"""verification question/answer split, handover tracking fields

Revision ID: 28aed61d4c9f
Revises: d17810f457fd
Create Date: 2026-06-21 05:37:11.126141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28aed61d4c9f'
down_revision = 'd17810f457fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handover_method', sa.Enum('cod', 'titik_aman', 'kurir'), nullable=True))
        batch_op.add_column(sa.Column('handover_location', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('handover_tracking', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('handover_status', sa.Enum('menunggu_metode', 'dalam_proses', 'selesai'), nullable=True))
        batch_op.add_column(sa.Column('handover_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_question', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('verification_answer', sa.String(length=500), nullable=True))
        batch_op.drop_column('secret_feature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_feature', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('verification_answer')
        batch_op.drop_column('verification_question')

    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_column('handover_completed_at')
        batch_op.drop_column('handover_status')
        batch_op.drop_column('handover_tracking')
        batch_op.drop_column('handover_location')
        batch_op.drop_column('handover_method')

    # ### end Alembic commands ###
